config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "foods#index"

  resources :foods do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end

  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
    self.data = [
      { id: 1, name: '--' },
      { id: 2, name: '丸の内・大手町・八重洲' },
      { id: 3, name: '銀座・有楽町・日比谷' },
      { id: 4, name: '新橋・汐留' },
      { id: 5, name: '神谷町・麻布台・御成門・愛宕' },
      { id: 6, name: '芝公園・芝・赤羽橋・三田' },
      { id: 7, name: '浜松町・竹芝・芝浦' },
      { id: 8, name: '品川・大崎・五反田・天王洲' },
      { id: 9, name: '日本橋・京橋' },
      { id: 10, name: '築地・月島・勝どき・晴海' },
      { id: 11, name: '台場・有明・豊洲・新木場' },
      { id: 12, name: '上野・浅草・蔵前・御徒町' },
      { id: 13, name: '浅草橋・両国・森下' },
      { id: 14, name: '押上・曳舟・向島' },
      { id: 15, name: '神田・秋葉原・お茶の水' },
      { id: 16, name: '神楽坂・飯田橋・江戸川橋' },
      { id: 17, name: '四谷・市ヶ谷・麹町・半蔵門' },
      { id: 18, name: '赤坂・永田町・溜池山王・虎ノ門' },
      { id: 19, name: '六本木・西麻布・麻布十番' },
      { id: 20, name: '広尾・天現寺・南麻布・元麻布' },
      { id: 21, name: '白金・高輪・四の橋' },
      { id: 22, name: '恵比寿・渋谷区東' },
      { id: 23, name: '青山・外苑前・乃木坂' },
      { id: 24, name: '原宿・表参道・神宮前' },
      { id: 25, name: '渋谷・松濤・神泉' },
      { id: 26, name: '代々木・千駄ヶ谷' },
      { id: 27, name: '新宿' },
      { id: 28, name: '富ヶ谷・代々木上原・下北沢' },
      { id: 29, name: '代官山' },
      { id: 30, name: '中目黒' },
      { id: 31, name: '目黒・学芸大学・祐天寺' },
      { id: 32, name: '池尻・三宿・駒沢・三軒茶屋' },
      { id: 33, name: '初台・幡ヶ谷・笹塚・代田橋' },
      { id: 34, name: '門前仲町・木場・清澄白河' },
      { id: 35, name: '高田馬場・目白・池袋' },
      { id: 36, name: '茅場町・八丁堀・新川' },
      { id: 37, name: '人形町・浜町・馬喰町' },
      { id: 38, name: '神保町・九段下・水道橋' },
      { id: 39, name: '自由が丘・都立大学' },
      { id: 40, name: 'その他' }
    ]

    include ActiveHash::Associations
    has_many :foods

end

app/models/business_form.rb
class BusinessForm < ActiveHash::Base
    self.data = [
      { id: 1, name: '--' },
      { id: 2, name: '実店舗' },
      { id: 3, name: '移動式店舗・屋台' },
      { id: 4, name: 'デリバリー' }
    ]

    include ActiveHash::Associations
    has_many :foods

    end

app/models/category.rb
class Category < ActiveHash::Base
    self.data = [
      { id: 1, name: '--' },
      { id: 2, name: 'チェーン系ファストフード' },
      { id: 3, name: 'カフェ' },
      { id: 4, name: 'フレンチ' },
      { id: 5, name: 'イタリアン' },
      { id: 6, name: 'スペイン・ポルトガル' },
      { id: 7, name: 'その他の西洋料理(アメリカ、メキシコ、北欧など)' },
      { id: 8, name: '寿司' },
      { id: 9, name: 'うどん・そば' },
      { id: 10, name: 'その他の和食' },
      { id: 11, name: '中華' },
      { id: 12, name: 'その他のアジア料理(韓国、タイ、ベトナムなど)' },
      { id: 13, name: '無国籍・創作' }
    ]

    include ActiveHash::Associations
    has_many :foods

    end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :food  # foodsテーブルとのアソシエーション
  belongs_to :user  # usersテーブルとのアソシエーション
end

app/models/evaluation.rb
class Evaluation < ActiveHash::Base
    self.data = [
      { id: 1, name: '--' },
      { id: 2, name: '５点：毎日でも購入したいくらい美味しい！！' },
      { id: 3, name: '４点：ぜひまた購入したい！' },
      { id: 4, name: '３点：機会があればまた購入しても良い' },
      { id: 5, name: '２点：２度目はないかな。' },
      { id: 6, name: '１点：購入したことを後悔している･･･' }
    ]

    include ActiveHash::Associations
    has_many :foods

    end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :area
  belongs_to_active_hash :business_form
  belongs_to_active_hash :evaluation

  validates :food_name, :restaurant, :category, :area, :business_form, :evaluation, :start_time, :price, presence: true
  validates :category_id, numericality: { other_than: 1 }
  validates :area_id, numericality: { other_than: 1 }
  validates :business_form_id, numericality: { other_than: 1 }
  validates :evaluation_id, numericality: { other_than: 1 }
  validates :price, numericality: { greater_than: 0, less_than: 9_999_999 }
  validates :price, format: { with: /\A[0-9]+\z/ }

  def self.search(search)
    if search != ""
      Food.where('food_name LIKE(?)', "%#{search}%")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :comments

  with_options presence: true do
    validates :name
    validates :email
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{6,100}+\z/, message: 'Include both letters and numbers' }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :favorite_food, :hate_food])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/foods/#{comment.food.id}"  # コメントと結びつくフード投稿の詳細画面に遷移する
  end
    
  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, food_id: params[:food_id])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  before_action :search_food, only: [:index, :search, :show]

  def index
    @newfoods = Food.includes(:user).where(created_at: Time.now.beginning_of_week..Time.now.end_of_week)
    @goodfoods = Food.includes(:user).where(evaluation_id: 2)
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @food.comments.includes(:user)
    @results = @p.result.includes(:user) 
  end

  def edit
    if @food.user == current_user 
      render :edit
    else
      redirect_to root_path
    end
  end

  def update
    if @food.update(food_params)
      redirect_to food_path
    else
      render :edit
    end
  end

  def destroy
    if @food.user == current_user
      @food.destroy
      redirect_to root_path
    end
  end

  def search
    @foods = Food.search(params[:keyword])
    @results = @p.result.includes(:user)  # 検索条件にマッチした商品の情報を取得
  end

  private

  def food_params
    params.require(:food).permit(:food_name, :restaurant, :review, :category_id, :area_id, :business_form_id, :evaluation_id, :price, :calorie, :image, :start_time).merge(user_id: current_user.id)
  end

  def set_food
    @food = Food.find(params[:id])
  end

  def search_food
    @p = Food.ransack(params[:q])  # 検索オブジェクトを生成
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @foods = user.foods
    @p = Food.ransack(params[:q])  # 検索オブジェクトを生成
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/edit.html.erb
<%# cssは新規投稿のものを併用しています。
app/assets/stylesheets/foods/new.css %>

<div class="foods-sell-contents">
  <header class="foods-sell-header">
    <%= link_to image_tag('tnd_logo.png' , size: '280x40'), "/" %>
  </header>
  <div class="foods-sell-main">
    <h2 class="foods-sell-title">フード情報を入力</h2>
    <%= form_with(model: @food, local: true) do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにする。%>
    <%= render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにする。%>

    <%# 料理画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        フード画像
        <span class="dispensable">任意</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"food-image" %>
      </div>
    </div>
    <%# /料理画像 %>
    <%# 料理名・店名・レビュー %>
    <div class="new-foods">
      <div class="weight-bold-text">
        料理名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :food_name, class:"foods-text", id:"food-name", placeholder:"料理名（必須 40文字まで)", maxlength:"40" %>
      <div class="weight-bold-text">
        レストラン名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :restaurant, class:"foods-text", id:"restaurant", placeholder:"レストラン名（必須 40文字まで)", maxlength:"40" %>
      <div class="foods-explain">
        <div class="weight-bold-text">
          料理の感想
          <span class="indispensable">任意</span>
        </div>
        <%= f.text_area :review, class:"foods-text", id:"review", placeholder:"料理の感想（必須 1,000文字まで）例）最近出店し始めた屋台のお店。低価格なのにボリュームがある。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /料理名・店名・レビュー %>

    <%# 料理の詳細 %>
    <div class="foods-detail">
      <div class="weight-bold-text">詳細情報</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"category"}) %>
        <div class="weight-bold-text">
          地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"area"}) %>
        <div class="weight-bold-text">
          販売形態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:business_form_id, BusinessForm.all, :id, :name, {}, {class:"select-box", id:"business-form"}) %>
        <div class="weight-bold-text">
          料理の評価
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:evaluation_id, Evaluation.all, :id, :name, {}, {class:"select-box", id:"evaluation"}) %>
      </div>
    </div>
    <%# /料理の詳細 %>

    <%# 購入額 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>購入額</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen"></span>
          <%= f.text_field :price, class:"price-input", id:"price", placeholder:"※半角数字     例）300" %>
          <span class="sell-yen">円</span>
        </div>
      </div>
    </div>
    <%# /購入額 %>

    <%# 摂取カロリー %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>摂取カロリー</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span class="dispensable">任意</span>
          </div>
          <span class="sell-yen"></span>
          <%= f.text_field :kalorie, class:"price-input", id:"kalorie", placeholder:"※半角数字     例）300" %>
          <span class="sell-yen">Kcal</span>
        </div>
      </div>
    </div>
    <%# /摂取カロリー %>

    <%# 購入日 %>
    <div class="foods-purchese-dates">
      <div class="weight-bold-text question-text">
        <span>購入日</span>
      </div>
      <div class="purchase-dates-content">
        <div class="price-text">
            <span class="indispensable">必須</span>
        </div>
        <%= raw sprintf(
                  f.date_select(
                    :start_time,
                    class:'select-birth',
                    id:"purchase-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 2020,
                    end_year: (Time.now.year + 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      </div>
    </div>
    <%# /購入日 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        また、投稿をもちまして
        <a href="#">投稿規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', food_path(@food.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="foods-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">東ナカ利用規約</a></li>
    </ul>
    <%= link_to image_tag('tnd_logo.png' , size: '210x30'), "/" %>
    <p class="inc">
      ©︎東京ナカ食DIARY
    </p>
  </footer>
</div>

app/views/foods/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      いつ、何食べた？
    </h2>
    <p class='service-explain'>
      東ナカはだれでもかんたんに投稿・検索できる
    </p>
    <p class='service-explain'>
      美味しいお店探しのアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の帯部分  %>


  <%# 東ナカの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      東ナカの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "スマホ投稿.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に投稿できる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に投稿・検索が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "kakeibo.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          日記、家計簿として使える
        </h3>
        <p class='feature-list-description'>
          自分の食事の傾向、使った食費が一目瞭然にわかる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "検索アイコン.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          食べたい物がすぐ見つかる
        </h3>
        <p class='feature-list-description'>
          自分が"今"いる場所で"今"食べたいものがすぐに見つかる！
        </p>
      </li>
    </ul>
  </div>
  <%# /東ナカの特徴 %>

  <%# 記事一覧 %>
  <div class='food-contents'>
    <h2 class='title'>注目のナカ食</h2>
    <%= link_to '今週の新着ナカ食', "#", class: "subtitle" %>
    <ul class='food-lists'>
      <% if @newfoods.presence %>
        <% @newfoods.each do |food| %>
         <li class='list'>
           <%= link_to food_path(food.id), method: :get do %>
             <div class='food-img-content'>
               <%= image_tag food.image, class: "food-img" if food.image.attached? %>

                 <div class='new'>
                   <span>New</span>
                 </div>

               <div class=food-name>
                 <span><%= food.user.name %>さん</span>
               </div>
             </div>
             <div class='food-info'>
               <h3 class='food-name'>
                 <%= food.food_name %>
               </h3>
               <h4 class='food-name'>
                 <%= food.restaurant %>
               </h4> 
               <div class='food-price'>
                 <span><%= food.price %>円<br>(税込み)</span>
                 <div class='star-btn'>
                   <%= image_tag "star.png", class:"star-icon" %>
                   <span class='star-count'>0</span>
                 </div>
               </div>
             </div>
           <% end %>
         </li>
        <% end %>
      <% end %>  

       <%# 記事がない場合のダミー %>
    <% unless @newfoods.presence %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
        <div class='food-info'>
          <h3 class='food-name'>
            記事を投稿してね！
          </h3>
          <div class='food-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>
      <%# /記事がない場合のダミー %>
    </ul>
     <%= link_to '高評価ナカ食', "#", class: "subtitle" %>
    <ul class='food-lists'>
      <% if @goodfoods.presence %>
        <% @goodfoods.each do |food| %>
         <li class='list'>
           <%= link_to food_path(food.id), method: :get do %>
             <div class='food-img-content'>
               <%= image_tag food.image, class: "food-img" if food.image.attached? %>

               <div class='hi-score'>
                   <span>満点</span>
                </div>

               <div class=food-name>
                 <span><%= food.user.name %>さん</span>
               </div>
             </div>
             <div class='food-info'>
               <h3 class='food-name'>
                 <%= food.food_name %>
               </h3>
               <h4 class='food-name'>
                 <%= food.restaurant %>
               </h4> 
               <div class='food-price'>
                 <span><%= food.price %>円<br>(税込み)</span>
                 <div class='star-btn'>
                   <%= image_tag "star.png", class:"star-icon" %>
                   <span class='star-count'>0</span>
                 </div>
               </div>
             </div>
           <% end %>
         </li>
        <% end %>
      <% end %>  

       <%# 記事がない場合のダミー %>
    <% unless @goodfoods.presence %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
        <div class='food-info'>
          <h3 class='food-name'>
            記事を投稿してね！
          </h3>
          <div class='food-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>
      <%# /記事がない場合のダミー %>
    </ul>
  </div>
  <%# /記事一覧 %>
</div>
<div class='purchase-btn'>
  <span class='purchase-btn-text'>投稿する</span>
  <a href="/foods/new">
    <%= image_tag 'folk_knife_icon.png' , size: '200x55' ,class: "purchase-btn-icon" %>
  </a>
</div>
<%= render "shared/footer" %>

app/views/foods/show.html.erb
<%= render "shared/header" %>

<%# 購入した料理の概要 %>
<div class="food-show">
  <div class="food-box">
    <h2 class="name">
      <%= @food.start_time %>
    </h2>
    <h3 class="name">
      <%= @food.food_name %>
    </h3>
    <div class='food-img-content'>
      <%= image_tag @food.image ,class:"food-box-img" %>
    </div>
    <div class="food-price-box">
      <span class="food-price">
        ￥<%= @food.price %>
      </span>
      <span class="food-postage">
        (税込み)
      </span>
      <span class="food-calorie">
        <%= @food.calorie %>Kcal
      </span>
    </div>

    <div class="food-explain-box">
      <span><%= @food.review %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-food">購入者</th>
          <td class="detail-value"><%= link_to @food.user.name, user_path(@food.user) %></td>
        </tr>
        <tr>
          <th class="detail-food">レストラン名</th>
          <td class="detail-value"><%= @food.restaurant %></td>
        </tr>
        <tr>
          <th class="detail-food">カテゴリー</th>
          <td class="detail-value"><%= @food.category.name %></td>
        </tr>
        <tr>
          <th class="detail-food">購入した地域</th>
          <td class="detail-value"><%= @food.area.name %></td>
        </tr>
        <tr>
          <th class="detail-food">販売形態</th>
          <td class="detail-value"><%= @food.business_form.name %></td>
        </tr>
        <tr>
          <th class="detail-food">評価</th>
          <td class="detail-value"><%= @food.evaluation.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切なナカ食の通報</span>
      </div>
    </div>
    <% if user_signed_in? %>
      <% if current_user.id == @food.user_id %>
          <%= link_to 'この日記を編集', edit_food_path(@food.id), method: :get, class: "food-red-btn" %>
          <p class='or-text'>or</p>
          <%= link_to 'この日記を削除', food_path(@food.id), method: :delete, class:'food-destroy' %>
      <% else %>
          <%= link_to '他の人も食べてる？', "#", class:"food-red-btn"%>
      <% end %>
    <% end %>
  </div>
  <%# /購入した料理の概要 %>

  <div class="comment-box">
    <div class="comments">
      <h3>⭐️このナカ食へのコメント⭐️</h3>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.name, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
    <% if current_user %>
      <%= form_with(model: [@food, @comment], local: true) do |form| %>
        <%= form.text_area :text, class:"comment-text", placeholder: "このナカ食へのコメントを記入", rows: "2" %>
        <%= form.submit "コメントを送信", class:"comment-btn" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>
  <div class="links">
    <a href="#" class="change-food-btn">
      ＜ 前のナカ食
    </a>
    <a href="#" class="change-food-btn">
      後ろのナカ食 ＞
    </a>
  </div>
  <a href="#" class='another-food'><%= @food.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>東京ナカ食DIARY</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("tnd_logo.png", class:"furima-icon"), "/" %>
    
    <form class="search-form" action="/foods/search">
      <input type="text" name="keyword" class='input-box' placeholder='キーワードから探す'>
      <button type="submit" class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
    
  </div>
  <div class='nav'>
    <ul class='lists-left'>
    <%= search_form_for @p, url: search_foods_path do |f| %>
      <%= f.label :category_id_eq, 'カテゴリー' %>
      <%= f.collection_select(:category_id_eq, Category.all, :id, :name, {}, {class:"nav-select-box", id:"category"}) %>
      <%= f.submit '検索' %>
    <% end %>
    <%= search_form_for @p, url: search_foods_path do |f| %>
      <%= f.label :area_id_eq, '地域　　　' %>
      <%= f.collection_select(:area_id_eq, Area.all, :id, :name, {}, {class:"nav-select-box", id:"area"}) %>
      <%= f.submit '検索' %>
    <% end %>
    </ul>

    <ul class='lists-right'>
      <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <% if user_signed_in? %>
        <li><%= link_to  current_user.name,  "/users/#{current_user.id}", class: "user-nickname" %></li> 
        <li><%= link_to "ログアウトする", destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
      <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>東ナカ利用規約</p>
  </div>
  <%= image_tag "tnd_logo.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("tnd_logo.png", class:"second-logo"), "/" %>
</header>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="food-show">
  <div class="food-box">
    <div class="mypage-username">
      <p><%= @name %>さんの日記</p>
    </div>
    <div class="food-cost">
     <p>今月の出費：<%= @foods.all.sum(:price) %>円</p>
   </div>
    <div class="calendar">
      <%= month_calendar events: @foods do |date, foods| %>
         <%= date.day %>

         <% foods.each do |food| %>
           <div>
            <%= link_to food.food_name, food %>
           </div>
         <% end %>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>